- name: Install Apache Web Server
  hosts: localhost
  become: true
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present
